data:
  raw_data_path: "data/1-raw/openpowerlifting-2025-09-27.csv"

  feature_engineer: "data/2-preprocessed/opl_preprocessed_not_IPF.csv"
  train_path: "data/3-features/opl_features_IPF"
  test_path: "data/3-features/opl_features_not_IPF.csv"

  model_output_path: "models/XGBR_model.pkl"

train_test_split:
  quantile: 0.8

preprocessing:
  handle_missing: "impute mean"
  categorical_encoding: "ordinal"

model:
  xgboost:
    tree_method: "hist"
    enable_categorical: True
    max_depth: 8
    learning_rate: 0.1
    n_estimators: 100
    subsample: 1
    colsample_bytree: 0.9
    reg_lambda: 100
    reg_alpha: 0.15
    gamma: 1
    random_state: 42

features:
  columns:
    - Age
    - BodyweightKg
    - prev_squat
    - prev_bench
    - prev_deadlift
    - avg_squat
    - avg_bench
    - avg_deadlift
    - days_since_last_meet
    - total_meets
    - percent_gain_since_last
    - career_avg_improvement_rate
    - total_std
